image: python:3.13

stages:
  - prepare
  - test

cache:
  paths:
    - .venv/

prepare-job:
  stage: prepare
  tags:
    - ubuntu:latest
    - large-fleet
  script:
    - |
        python3 -m venv .venv
        source .venv/bin/activate
        pip install -r requirements-dev.txt
  artifacts:
    paths:
      - .venv/

unit-test-job:
  stage: test
  tags:
    - ubuntu:latest
    - large-fleet
  dependencies:
    - prepare-job
  before_script:
    - source .venv/bin/activate
  script:
    - |
      python -m coverage run -m unittest discover -s tests
      python -m coverage report --fail-under=100

py-test-job:
  stage: test
  tags:
    - ubuntu:latest
    - large-fleet
  dependencies:
    - prepare-job
  before_script:
    - source .venv/bin/activate
  script:
    - |
      python -m coverage run -m pytest --junitxml=pytest-results.xml
      coverage xml -o coverage.xml
      python -m coverage report --fail-under=100
  artifacts:
    when: always
    reports:
      junit: pytest-results.xml
    paths:
      - pytest-results.xml
      - coverage.xml

lint-ruff-test-job:
  stage: test
  tags:
    - ubuntu:latest
    - large-fleet
  dependencies:
    - prepare-job
  before_script:
    - source .venv/bin/activate
  script:
    - ruff check .

lint-mypy-test-job:
  stage: test
  tags:
    - ubuntu:latest
    - large-fleet
  dependencies:
    - prepare-job
  before_script:
    - source .venv/bin/activate
  script:
    - mypy application_name


formatting-test-job:
  stage: test
  tags:
    - ubuntu:latest
    - large-fleet
  dependencies:
    - prepare-job
  before_script:
    - source .venv/bin/activate
  script:
    - black  --check .
