name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements-dev.txt
        cache:
          paths: .venv

  unit-test:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - name: Activate virtual environment
        run: source .venv/bin/activate
      - name: Run unit tests
        run: |
          python -m coverage run -m unittest discover -s tests
          python -m coverage report --fail-under=100

  py-test:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - name: Activate virtual environment
        run: source .venv/bin/activate
      - name: Run pytest
        run: |
          python -m coverage run -m pytest --junitxml=pytest-results.xml
          coverage xml -o coverage.xml
          python -m coverage report --fail-under=100
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: pytest-results.xml
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  lint-ruff:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - name: Activate virtual environment
        run: source .venv/bin/activate
      - name: Run ruff
        run: ruff check .

  lint-mypy:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - name: Activate virtual environment
        run: source .venv/bin/activate
      - name: Run mypy
        run: mypy application_name

  formatting:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - name: Activate virtual environment
        run: source .venv/bin/activate
      - name: Check formatting
        run: black --check .
