name: Create Dynamic Branch on New Issue
on:
  issues:
    types: [opened]
jobs:
  create-branch:
    name: "Create Dynamic Branch"
    runs-on: ubuntu-latest
    steps:
      - name: Set Branch Name
        id: set-branch-name
        run: |
          # Generate a dynamic branch name based on the current date and time
          branch_name="${{ github.event.issue.title }}"
          echo "::set-output name=branch_name::$branch_name"
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Create Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Retrieve the branch name from the previous step's output
          branch_name=${{ steps.set-branch-name.outputs.branch_name }}
          git checkout -b $branch_name
          git push --set-upstream origin $branch_name